print("You open your eyes, to find yourself laying down in the dirt, you can feel it warm beneath you. Sitting up you see a cloaked figure slide out of the shadows.\n")
print("\"What is your name travller?\"\n")
name = input()
print("\n")
print("\"Welcome " +name+ ". Today is the day that you begin your journey. Before you go you must pick what you will take with you.\"The figure infront of you points behind them.\n")
print("Press Any Key to continue")
continue1 = input()
print("You get up and dust yourself off, looking behind the figure you see three items.")
print("First you see ")